
version: '3'

services:
  php-app:
    image: registry.nexusdeploy.com/public/test:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - monitoring
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    deploy:
      restart_policy:
        condition: any
      mode: global


networks:
  monitoring:
    external: true