services:
  php-app:
    image: registry.nexusdeploy.com/public/test:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - test-app-mongo
    ports:
      - "80:80"
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.application == true

  # MongoDB for development
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb-root-user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb-root-password
    volumes:
      - mongodb-data:/data/db
    secrets:
      - source: mongodb-root-user
        target: /run/secrets/mongodb-root-user
        mode: 0644
      - source: mongodb-root-password
        target: /run/secrets/mongodb-root-password
        mode: 0644
    networks:
      - test-app-mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.database == true

secrets:
  mongodb-root-user:
    external: true
  mongodb-root-password:
    external: true

volumes:
  mongodb-data:
    external: true

networks:
  test-app-mongo:
    external: true