services:
  php-app:
    image: registry.nexusdeploy.com/public/test:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - monitoring
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any


networks:
  monitoring:
    external: true