name: Deploy to Docker Swarm

on:
  push:
    branches: [ main, master ]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GITHUB_REPOSITORY_NAME: ${{ github.repository_owner }}/php-hello-world
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SWARM_MANAGER_IP: ${{ secrets.SWARM_MANAGER_IP }}
  SWARM_MANAGER_USER: ${{ secrets.SWARM_MANAGER_USER }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1