name: Empty Workflow

# Workflow'un çalışacağı olaylar
on:
  # Manuel tetikleme için workflow_dispatch ekledim
  workflow_dispatch:
  # İsterseniz aşağıdaki satırları yorum işaretinden çıkararak diğer tetikleyicileri ekleyebilirsiniz
  push:
     branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]

# İzinleri en aza indiriyoruz
permissions: {}

jobs:
  empty-job:
    name: Empty Job
    runs-on: ubuntu-latest
    steps:
      # Tek bir adım ekledim ama bu adım da hiçbir şey yapmıyor
      - name: Do Nothing
        run: echo "This workflow does nothing"

      - name: Checkout code
        uses: actions/checkout@v2