name: Deploy to Docker Swarm

on:
  push:
    branches: [ main, master ]

env:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GITHUB_REPOSITORY_NAME: ${{ github.repository_owner }}/php-hello-world
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SWARM_MANAGER_IP: ${{ secrets.SWARM_MANAGER_IP }}
  SWARM_MANAGER_USER: ${{ secrets.SWARM_MANAGER_USER }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:${{ env.IMAGE_TAG }},${{ env.DOCKER_REGISTRY }}/${{ env.GITHUB_REPOSITORY_NAME }}:latest

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ env.SWARM_MANAGER_IP }} >> ~/.ssh/known_hosts

      - name: Copy docker-compose.yml to swarm manager
        run: |
          envsubst < docker-compose.yml > docker-compose.deployed.yml
          scp docker-compose.deployed.yml ${{ env.SWARM_MANAGER_USER }}@${{ env.SWARM_MANAGER_IP }}:~/docker-compose.yml

      - name: Deploy to Docker Swarm
        run: |
          ssh ${{ env.SWARM_MANAGER_USER }}@${{ env.SWARM_MANAGER_IP }} "docker stack deploy -c ~/docker-compose.yml php-hello-world --with-registry-auth"